//! # D-Bus interface proxy for: `com.steampowered.SteamOSManager1.HdmiCec2`
//!
//! This code was generated by `zbus-xmlgen` `5.3.1` from D-Bus introspection data.
//! Source: `com.steampowered.SteamOSManager1.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.steampowered.SteamOSManager1.HdmiCec2",
    assume_defaults = true
)]
pub trait HdmiCec2 {
    /// EnableControl property
    #[zbus(property)]
    fn enable_control(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_enable_control(&self, value: bool) -> zbus::Result<()>;

    /// SuspendDevice property
    #[zbus(property)]
    fn suspend_device(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_suspend_device(&self, value: bool) -> zbus::Result<()>;

    /// SuspendTv property
    #[zbus(property)]
    fn suspend_tv(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_suspend_tv(&self, value: bool) -> zbus::Result<()>;

    /// WakeDevice property
    #[zbus(property)]
    fn wake_device(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_wake_device(&self, value: bool) -> zbus::Result<()>;

    /// WakeDeviceSupported property
    #[zbus(property)]
    fn wake_device_supported(&self) -> zbus::Result<bool>;

    /// WakeTv property
    #[zbus(property)]
    fn wake_tv(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_wake_tv(&self, value: bool) -> zbus::Result<()>;
}
